\section{CALICE::BadDataException Class Reference}
\label{classCALICE_1_1BadDataException}\index{CALICE::BadDataException@{CALICE::BadDataException}}


exception to be thrown when data leads to a conflict  


{\ttfamily \#include $<$CaliceException.hh$>$}\subsection*{Public Member Functions}
\begin{DoxyCompactItemize}
\item 
{\bfseries BadDataException} (std::string text)  throw ()\label{classCALICE_1_1BadDataException_a765bc2673e0be6a8371b058b3fbe4a4e}

\item 
const char $\ast$ {\bfseries what} () const   throw ()\label{classCALICE_1_1BadDataException_aee526e91ff2f998e8420baac9c070546}

\end{DoxyCompactItemize}
\subsection*{Protected Attributes}
\begin{DoxyCompactItemize}
\item 
std::string {\bfseries \_\-message}\label{classCALICE_1_1BadDataException_aca1e20b6d7f88c0cd5dbacb38b462386}

\end{DoxyCompactItemize}


\subsection{Detailed Description}
exception to be thrown when data leads to a conflict 

Definition at line 37 of file CaliceException.hh.

The documentation for this class was generated from the following file:\begin{DoxyCompactItemize}
\item 
CaliceException.hh\end{DoxyCompactItemize}
